# Generated by Django 6.0 on 2026-09-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="line",
            field=models.CharField(
                choices=[
                    ("verao", "Verão / Calor (Red Line)"),
                    ("inverno", "Inverno / Frio (Blue Line)"),
                ],
                db_index=True,
                default="verao",
                max_length=10,
                verbose_name="Linha",
            ),
        ),
    ]
