# Generated by Django 6.0 on 2026-09-22 19:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(
                blank=True, default="", max_length=60, verbose_name="Cor"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="drive_file_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=128,
                null=True,
                unique=True,
                verbose_name="ID do arquivo no Google Drive",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(
                blank=True, default="", verbose_name="URL da imagem (Drive)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="size_range",
            field=models.CharField(
                blank=True, default="", max_length=60, verbose_name="Tamanhos"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="wholesale_price_24",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Caixa 24+ peças",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="wholesale_price_6",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Atacado 6+ peças",
            ),
        ),
    ]
