# Generated by Django 6.0.8 on 2026-09-29 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_color_product_drive_file_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="line",
            field=models.CharField(
                blank=True,
                choices=[("verao", "Verão / Calor"), ("inverno", "Inverno / Frio")],
                db_index=True,
                default="",
                help_text="Aba em que a subcategoria aparece. Vazio = detectada pelos produtos.",
                max_length=10,
                verbose_name="Linha (estação)",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Deixe vazio para categoria principal; preencha para torná-la subcategoria.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subcategories",
                to="products.category",
                verbose_name="Categoria pai",
            ),
        ),
    ]
