# Generated by Django 6.0.8 on 2026-09-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_color_product_drive_file_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="drive_file_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Nome do arquivo no Drive",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="drive_md5",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                verbose_name="Checksum da imagem no Drive",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.URLField(
                blank=True, default="", verbose_name="URL externa da imagem (legado)"
            ),
        ),
    ]
