# Generated by Django 6.0.8 on 2026-09-30 01:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0004_category_parent_line"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="Cliente"
                    ),
                ),
                ("total_qty", models.PositiveIntegerField(default=0)),
                (
                    "tier",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Faixa de preço",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("novo", "Novo (enviado ao WhatsApp)"),
                            ("confirmado", "Confirmado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="novo",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "pedido",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("line", models.CharField(blank=True, default="", max_length=10)),
                ("size", models.CharField(blank=True, default="", max_length=20)),
                ("color", models.CharField(blank=True, default="", max_length=60)),
                ("qty", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
